/* Generated by GOB (v2.0.20)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>


#include <glib.h>

#ifndef __GIV_SETTINGS_H__
#define __GIV_SETTINGS_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define GIV_TYPE_SETTINGS	(giv_settings_get_type())
#define GIV_SETTINGS(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), giv_settings_get_type(), GivSettings)
#define GIV_SETTINGS_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), giv_settings_get_type(), GivSettings const)
#define GIV_SETTINGS_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), giv_settings_get_type(), GivSettingsClass)
#define GIV_IS_SETTINGS(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), giv_settings_get_type ())

#define GIV_SETTINGS_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), giv_settings_get_type(), GivSettingsClass)

/* Private structure type */
typedef struct _GivSettingsPrivate GivSettingsPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GIV_SETTINGS__
#define __TYPEDEF_GIV_SETTINGS__
typedef struct _GivSettings GivSettings;
#endif
struct _GivSettings {
	GObject __parent__;
	/*< public >*/
	gboolean do_same_filetype_on_next;
	gboolean default_show_subpixel;
	gboolean default_auto_resize;
	gboolean default_auto_contrast;
	/*< private >*/
	GivSettingsPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _GivSettingsClass GivSettingsClass;
struct _GivSettingsClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	giv_settings_get_type	(void) G_GNUC_CONST;
#line 25 "src/giv-settings.gob"
GObject * 	giv_settings_new	(const char * keyfile_path);
#line 65 "giv-settings.h"
#line 64 "src/giv-settings.gob"
int 	giv_settings_save_prefs	(GivSettings * self);
#line 68 "giv-settings.h"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
